from fermigates.base import (
    BaseFermiBackbone,
    BaseFermiClassifier,
    BaseFermiLayer,
    BaseFermiModel,
    SparsitySummary,
)
from fermigates.export import (
    LayerPruningReport,
    ModelPruningReport,
    hard_mask_module_weights_,
    hard_masked_state_dict,
    pruning_report,
    to_hard_masked_model,
)
from fermigates.gates import (
    BaseGate,
    BinaryConcreteGate,
    FermiGate,
    GompertzGate,
    GroupLassoGate,
    HardConcreteGate,
    MagnitudeGate,
)
from fermigates.layers import (
    FermiGatedConv2d,
    FermiGatedLinear,
    FermiMLPBlock,
    FermiResidualBlock,
    FermiTransformerEncoderLayer,
    LinearCalibration,
)
from fermigates.losses import (
    FermiLossBreakdown,
    binary_entropy_loss,
    budget_penalty_loss,
    consistency_loss,
    fermi_free_energy_loss,
    fermi_informed_loss,
    group_sparsity_l21_loss,
    hoyer_sparsity_loss,
    hoyer_sparsity_score,
    kl_to_bernoulli_prior_loss,
    sparsity_l1_loss,
)
from fermigates.masks import FermiMask, GompertzMask, GroupLassoMask, MagnitudeMask
from fermigates.metrics import (
    FreeEnergyComponents,
    LayerOccupancyMetrics,
    MetricsTracker,
    ModelOccupancyMetrics,
    collect_gate_metrics,
    free_energy_components,
)
from fermigates.models import FermiConvClassifier, FermiMLPClassifier, FermiTransformerClassifier
from fermigates.training import (
    AdaptiveBudgetController,
    AnnealingSchedule,
    AnnealingState,
    FermiAnnealingPlan,
)

__version__ = "0.2.0"

__all__ = [
    "__version__",
    "SparsitySummary",
    "BaseFermiLayer",
    "BaseFermiModel",
    "BaseFermiBackbone",
    "BaseFermiClassifier",
    "BaseGate",
    "FermiGate",
    "BinaryConcreteGate",
    "HardConcreteGate",
    "MagnitudeGate",
    "GroupLassoGate",
    "GompertzGate",
    "FermiMask",
    "MagnitudeMask",
    "GroupLassoMask",
    "GompertzMask",
    "LinearCalibration",
    "FermiGatedLinear",
    "FermiGatedConv2d",
    "FermiMLPBlock",
    "FermiResidualBlock",
    "FermiTransformerEncoderLayer",
    "FermiLossBreakdown",
    "fermi_informed_loss",
    "fermi_free_energy_loss",
    "binary_entropy_loss",
    "sparsity_l1_loss",
    "budget_penalty_loss",
    "consistency_loss",
    "kl_to_bernoulli_prior_loss",
    "group_sparsity_l21_loss",
    "hoyer_sparsity_loss",
    "hoyer_sparsity_score",
    "AnnealingSchedule",
    "AnnealingState",
    "FermiAnnealingPlan",
    "AdaptiveBudgetController",
    "LayerPruningReport",
    "ModelPruningReport",
    "hard_mask_module_weights_",
    "hard_masked_state_dict",
    "to_hard_masked_model",
    "pruning_report",
    "LayerOccupancyMetrics",
    "ModelOccupancyMetrics",
    "FreeEnergyComponents",
    "collect_gate_metrics",
    "free_energy_components",
    "MetricsTracker",
    "FermiMLPClassifier",
    "FermiConvClassifier",
    "FermiTransformerClassifier",
]
